version: '4'

services:
  bot:
    build:
      context: .
      dockerfile: buildfiles/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always
  redis:
    image: redis
    env_file:
      - .env
    restart: always
  db:
    image: mariadb
    volumes:
      - mysql_data:/var/lib/mariadb/data/
    env_file:
      - .env.prod.db
    restart: always
    ports:
      - "6379:6379"
  worker:
    build:
      context: .
      dockerfile: buildfiles/scheduler.dockerfile
    env_file:
      - .env
    depends_on:
      - redis
      - bot
    restart: always

volumes:
  mysql_data: